In [17]:
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

In [18]:
summermonths_df = pd.read_excel('summer_23.xlsx')
summermonths_df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
315653,A579E97D03366092,classic_bike,2023-08-27 18:49:28,2023-08-27 19:03:08,Journal Square,JC103,Riverview Park,JC057,40.733767,-74.062441,40.744319,-74.043991,member
315654,5A86269B2A06457D,classic_bike,2023-08-12 11:49:02,2023-08-12 12:15:05,Journal Square,JC103,City Hall - Washington St & 1 St,HB105,40.733670,-74.062500,40.737360,-74.030970,member
315655,B2BF13B8AC5129AB,classic_bike,2023-08-01 18:53:29,2023-08-01 19:09:03,Journal Square,JC103,Riverview Park,JC057,40.733670,-74.062500,40.744319,-74.043991,member
315656,3E126EFFE4F64E4D,classic_bike,2023-08-14 11:36:10,2023-08-14 11:57:15,Journal Square,JC103,Manila & 1st,JC082,40.733702,-74.062508,40.721651,-74.042884,member
315657,3D4074EAA1A43EC8,classic_bike,2023-08-17 13:30:35,2023-08-17 13:57:17,Journal Square,JC103,Exchange Pl,JC116,40.733670,-74.062500,40.716366,-74.034344,member

In [19]:
wintermonths_df = pd.read_excel('winter_234.xlsx')
wintermonths_df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
164949,B4251D3376B59FF2,electric_bike,2024-02-25 09:38:44,2024-02-25 09:46:36,Bergen Ave & Sip Ave,JC109,Newark Ave,JC032,40.731154,-74.064473,40.721525,-74.046305,member
164950,513FF14445FD5A5E,electric_bike,2024-02-26 11:52:05,2024-02-26 12:00:49,Bergen Ave & Sip Ave,JC109,Newark Ave,JC032,40.730872,-74.064368,40.721525,-74.046305,member
164951,87DBD5B9091DFEC3,electric_bike,2024-02-05 17:05:38,2024-02-05 17:07:54,Montgomery St,JC099,Newark Ave,JC032,40.719487,-74.050998,40.721525,-74.046305,member
164952,8DD48EA418BCA621,electric_bike,2024-02-22 18:42:50,2024-02-22 18:46:39,York St & Marin Blvd,JC097,Newark Ave,JC032,40.719073,-74.043205,40.721525,-74.046305,member
164953,9F03340617826524,classic_bike,2024-02-28 08:39:10,2024-02-28 08:42:47,Dixon Mills,JC076,Newark Ave,JC032,40.721630,-74.049968,40.721525,-74.046305,member

In [20]:
summerwinter_df = pd.concat([summermonths_df, wintermonths_df])

summerwinter_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
164949,B4251D3376B59FF2,electric_bike,2024-02-25 09:38:44,2024-02-25 09:46:36,Bergen Ave & Sip Ave,JC109,Newark Ave,JC032,40.731154,-74.064473,40.721525,-74.046305,member
164950,513FF14445FD5A5E,electric_bike,2024-02-26 11:52:05,2024-02-26 12:00:49,Bergen Ave & Sip Ave,JC109,Newark Ave,JC032,40.730872,-74.064368,40.721525,-74.046305,member
164951,87DBD5B9091DFEC3,electric_bike,2024-02-05 17:05:38,2024-02-05 17:07:54,Montgomery St,JC099,Newark Ave,JC032,40.719487,-74.050998,40.721525,-74.046305,member
164952,8DD48EA418BCA621,electric_bike,2024-02-22 18:42:50,2024-02-22 18:46:39,York St & Marin Blvd,JC097,Newark Ave,JC032,40.719073,-74.043205,40.721525,-74.046305,member
164953,9F03340617826524,classic_bike,2024-02-28 08:39:10,2024-02-28 08:42:47,Dixon Mills,JC076,Newark Ave,JC032,40.721630,-74.049968,40.721525,-74.046305,member

In [21]:
summerwinter_df.to_excel("summerwinter_23_4.xlsx", index=False)