In [1]:
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

In [2]:
june23_df = pd.read_excel('June23.xlsx')
june23_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member

In [3]:
july23_df = pd.read_excel('July23.xlsx')
july23_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7A68381621C25F78,classic_bike,2023-07-17 17:16:34,2023-07-17 17:20:52,Astor Place,JC077,Communipaw & Berry Lane,JC084,40.719225,-74.071281,40.714358,-74.066611,member
1,0F814CA67B2FA120,classic_bike,2023-07-26 19:40:15,2023-07-26 19:44:37,Adams St & 2 St,HB407,9 St HBLR - Jackson St & 8 St,HB305,40.739727,-74.036866,40.747907,-74.038412,member
2,775A38967EBF5FB4,electric_bike,2023-07-01 12:12:22,2023-07-01 12:27:45,McGinley Square,JC055,Riverview Park,JC057,40.725340,-74.067622,40.744319,-74.043991,member
3,D93B742DCE1C1447,classic_bike,2023-07-20 19:10:18,2023-07-20 19:17:22,Baldwin at Montgomery,JC020,Brunswick St,JC023,40.723455,-74.064359,40.724176,-74.050656,member
4,AA7A6863B4B92169,electric_bike,2023-07-07 19:33:59,2023-07-07 19:58:17,Baldwin at Montgomery,JC020,Mama Johnson Field - 4 St & Jackson St,HB404,40.723659,-74.064194,40.743140,-74.040041,casual

In [5]:
aug23_df = pd.read_excel('Aug23.xlsx')
aug23_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E2E964A161F786AB,classic_bike,2023-08-07 19:37:47,2023-08-07 19:41:14,6 St & Grand St,HB302,Madison St & 10 St,HB503,40.744398,-74.034501,40.749943,-74.035865,member
1,0660F2E48E3BB87F,classic_bike,2023-08-01 13:16:22,2023-08-01 13:26:02,6 St & Grand St,HB302,6 St & Grand St,HB302,40.744398,-74.034501,40.744398,-74.034501,member
2,940FC7C675232897,classic_bike,2023-08-15 17:28:23,2023-08-15 17:50:35,Heights Elevator,JC059,Heights Elevator,JC059,40.748721,-74.040480,40.748716,-74.040443,member
3,E967660CC5CD585B,classic_bike,2023-08-01 12:44:24,2023-08-01 12:49:45,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - River St & Hudson Pl,HB102,40.735279,-74.046830,40.736068,-74.029127,member
4,D997CB0B855FE2D6,classic_bike,2023-08-08 12:31:16,2023-08-08 12:40:18,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - River St & Hudson Pl,HB102,40.735208,-74.046964,40.736068,-74.029127,member

In [6]:
summer_df = pd.concat([june23_df, july23_df, aug23_df])

summer_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112022,A579E97D03366092,classic_bike,2023-08-27 18:49:28,2023-08-27 19:03:08,Journal Square,JC103,Riverview Park,JC057,40.733767,-74.062441,40.744319,-74.043991,member
112023,5A86269B2A06457D,classic_bike,2023-08-12 11:49:02,2023-08-12 12:15:05,Journal Square,JC103,City Hall - Washington St & 1 St,HB105,40.733670,-74.062500,40.737360,-74.030970,member
112024,B2BF13B8AC5129AB,classic_bike,2023-08-01 18:53:29,2023-08-01 19:09:03,Journal Square,JC103,Riverview Park,JC057,40.733670,-74.062500,40.744319,-74.043991,member
112025,3E126EFFE4F64E4D,classic_bike,2023-08-14 11:36:10,2023-08-14 11:57:15,Journal Square,JC103,Manila & 1st,JC082,40.733702,-74.062508,40.721651,-74.042884,member
112026,3D4074EAA1A43EC8,classic_bike,2023-08-17 13:30:35,2023-08-17 13:57:17,Journal Square,JC103,Exchange Pl,JC116,40.733670,-74.062500,40.716366,-74.034344,member

In [ ]:
summer_df.tail()

In [7]:
summer_df.to_excel("summer_23.xlsx", index=False)